spring:
  application:
    name: demo
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./tools/h2/mydb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    platform: h2
    username: tang
    password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.example.demo.util.ListTypeHandler